name: extended_formz
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.1
  formz: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: