name: api_generator_example
description: A new Flutter package project.
version: 0.0.3
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  api_annotations: null
  dio: ^4.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.0

dev_dependencies:
  api_generator: null
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4

dependency_overrides:
  api_annotations:
    path: ../annotations
  api_generator:
    path: ../generator

flutter: null
